server:
  port:  ${PORT}

spring:
  application:
    name: RSTECHtestovoe

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      boot:
        allow_jdbc_metadata_access=false
    hibernate:
      show-sql: true

  liquibase:
    change-log: db/changelog/changelog-master.yaml

api:
  product-images:
    path: product-images/